Update README.md
Erik-Lamers1/vnet-manager pull request #15
Opened 2020-11-06 18:14 UTC by SyntheticOxygen

Hi, i think it is good to add documentation of how additional packages in the base container can be installed, and how to destroy and recreate a base container.

2020-11-06 18:59 UTC, Erik-Lamers1 requested changes

2020-11-06 18:59 UTC, Erik-Lamers1 commented on README.md
> +$ vnet-manager create
Idem

2020-11-06 18:59 UTC, Erik-Lamers1 commented on README.md
> +$ vnet-manager destroy -b
This needs a config file to be passed

2020-11-09 11:14 UTC, SyntheticOxygen commented
Updated the two errors.

2020-11-09 12:00 UTC, Erik-Lamers1 approved these changes

2020-11-09 12:00 UTC, merged